name: Fetch Utilities from RateAcuity

on:
  workflow_dispatch: # Run manually from GitHub UI

jobs:
  fetch-and-insert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run fetch script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        RATE_ACUITY_USERNAME: ${{ secrets.RATE_ACUITY_USERNAME }}
        RATE_ACUITY_PASSWORD: ${{ secrets.RATE_ACUITY_PASSWORD }}
      run: python main.py
